/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiTodosRouteImport } from './routes/api/todos'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiDashboardsRouteImport } from './routes/api/dashboards'
import { Route as ApiDashboardWidgetsRouteImport } from './routes/api/dashboard-widgets'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedDashboardsIndexRouteImport } from './routes/_authenticated/dashboards/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedProjectProjectIdRouteImport } from './routes/_authenticated/project/$projectId'
import { Route as AuthenticatedDashboardDashboardIdRouteImport } from './routes/_authenticated/dashboard/$dashboardId'

const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTodosRoute = ApiTodosRouteImport.update({
  id: '/api/todos',
  path: '/api/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardsRoute = ApiDashboardsRouteImport.update({
  id: '/api/dashboards',
  path: '/api/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardWidgetsRoute = ApiDashboardWidgetsRouteImport.update({
  id: '/api/dashboard-widgets',
  path: '/api/dashboard-widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardsIndexRoute =
  AuthenticatedDashboardsIndexRouteImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectProjectIdRoute =
  AuthenticatedProjectProjectIdRouteImport.update({
    id: '/project/$projectId',
    path: '/project/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardDashboardIdRoute =
  AuthenticatedDashboardDashboardIdRouteImport.update({
    id: '/dashboard/$dashboardId',
    path: '/dashboard/$dashboardId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/api/dashboard-widgets': typeof ApiDashboardWidgetsRoute
  '/api/dashboards': typeof ApiDashboardsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/users': typeof ApiUsersRoute
  '/dashboard/$dashboardId': typeof AuthenticatedDashboardDashboardIdRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/api/dashboard-widgets': typeof ApiDashboardWidgetsRoute
  '/api/dashboards': typeof ApiDashboardsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/users': typeof ApiUsersRoute
  '/': typeof AuthenticatedIndexRoute
  '/dashboard/$dashboardId': typeof AuthenticatedDashboardDashboardIdRoute
  '/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboards': typeof AuthenticatedDashboardsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/api/dashboard-widgets': typeof ApiDashboardWidgetsRoute
  '/api/dashboards': typeof ApiDashboardsRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/todos': typeof ApiTodosRoute
  '/api/users': typeof ApiUsersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard/$dashboardId': typeof AuthenticatedDashboardDashboardIdRoute
  '/_authenticated/project/$projectId': typeof AuthenticatedProjectProjectIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/dashboards/': typeof AuthenticatedDashboardsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/presentation'
    | '/api/dashboard-widgets'
    | '/api/dashboards'
    | '/api/projects'
    | '/api/todos'
    | '/api/users'
    | '/dashboard/$dashboardId'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboards/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/presentation'
    | '/api/dashboard-widgets'
    | '/api/dashboards'
    | '/api/projects'
    | '/api/todos'
    | '/api/users'
    | '/'
    | '/dashboard/$dashboardId'
    | '/project/$projectId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboards'
    | '/projects'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/presentation'
    | '/api/dashboard-widgets'
    | '/api/dashboards'
    | '/api/projects'
    | '/api/todos'
    | '/api/users'
    | '/_authenticated/'
    | '/_authenticated/dashboard/$dashboardId'
    | '/_authenticated/project/$projectId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_authenticated/dashboards/'
    | '/_authenticated/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PresentationRoute: typeof PresentationRoute
  ApiDashboardWidgetsRoute: typeof ApiDashboardWidgetsRoute
  ApiDashboardsRoute: typeof ApiDashboardsRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiTodosRoute: typeof ApiTodosRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/todos': {
      id: '/api/todos'
      path: '/api/todos'
      fullPath: '/api/todos'
      preLoaderRoute: typeof ApiTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboards': {
      id: '/api/dashboards'
      path: '/api/dashboards'
      fullPath: '/api/dashboards'
      preLoaderRoute: typeof ApiDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard-widgets': {
      id: '/api/dashboard-widgets'
      path: '/api/dashboard-widgets'
      fullPath: '/api/dashboard-widgets'
      preLoaderRoute: typeof ApiDashboardWidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboards/': {
      id: '/_authenticated/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AuthenticatedDashboardsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/project/$projectId': {
      id: '/_authenticated/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$dashboardId': {
      id: '/_authenticated/dashboard/$dashboardId'
      path: '/dashboard/$dashboardId'
      fullPath: '/dashboard/$dashboardId'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardDashboardIdRoute: typeof AuthenticatedDashboardDashboardIdRoute
  AuthenticatedProjectProjectIdRoute: typeof AuthenticatedProjectProjectIdRoute
  AuthenticatedDashboardsIndexRoute: typeof AuthenticatedDashboardsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDashboardDashboardIdRoute:
    AuthenticatedDashboardDashboardIdRoute,
  AuthenticatedProjectProjectIdRoute: AuthenticatedProjectProjectIdRoute,
  AuthenticatedDashboardsIndexRoute: AuthenticatedDashboardsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PresentationRoute: PresentationRoute,
  ApiDashboardWidgetsRoute: ApiDashboardWidgetsRoute,
  ApiDashboardsRoute: ApiDashboardsRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiTodosRoute: ApiTodosRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
